spring.application.name=faturamaroc-backend

# PostgreSQL Database Configuration (Auto-détecté par Spring Boot via l'URL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/faturamaroc_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Jackson & Timezone (Maroc)
spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Africa/Casablanca
